### ISSUE TITLE
Sai danh sách mới cập nhật

### ISSUE THREAD

**Issue by tuhm1** [TNTKien/suicaodex#19]
![suicaodex-issue](https://github.com/user-attachments/assets/4dc6096e-4830-4e99-91fd-90390717d694)

![suicaodex-issue-2](https://github.com/user-attachments/assets/19f21772-8d26-4085-87f6-6c956e112abc)

Do `manga` endpoint tính cả cập nhật chapter trong ngôn ngữ khác. Bro có thể dùng `chapter` endpoint với `translatedLanguage` là `"vi"`.

**Comment by TNTKien** [comment]
Cảm ơn bạn đã báo lỗi! Đây vốn là lỗi tồn đọng từ những ngày đâu.
Tôi đã sửa lại đồng thời thiết kế lại giao diện cho "giống" MangaDex hơn 🐧
Do cache nên có thể chưa cập nhật được ngay, bạn có thể xem tạm [tại đây](https://suicaodex.com/?v=nihahahaha)
